from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional
from uuid import uuid4

from pydantic import BaseModel, Field


# ── Enums ───────────────────────────────────────────────────────


class Severity(str, Enum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class InvestigationStatus(str, Enum):
    DETECTING = "detecting"
    PLANNING = "planning"
    INVESTIGATING = "investigating"
    DECIDING = "deciding"
    ACTING = "acting"
    REPORTING = "reporting"
    COMPLETED = "completed"
    FAILED = "failed"


class ServiceName(str, Enum):
    API_GATEWAY = "api-gateway"
    CHECKOUT_SERVICE = "checkout-service"
    PAYMENT_GATEWAY = "payment-gateway"
    INVENTORY_SERVICE = "inventory-service"
    USER_AUTH = "user-auth"
    NOTIFICATION_SERVICE = "notification-service"
    POSTGRES_DB = "postgres-db"
    REDIS_CACHE = "redis-cache"


class ChangeType(str, Enum):
    CONFIG_CHANGE = "config_change"
    CODE_DEPLOY = "code_deploy"
    SCALING_EVENT = "scaling_event"
    ROLLBACK = "rollback"


# ── Core Data Models ────────────────────────────────────────────


class Alert(BaseModel):
    alert_id: str = Field(default_factory=lambda: uuid4().hex[:12])
    service: ServiceName
    metric: str
    value: float
    threshold: float
    severity: Severity
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    description: str


class LogEntry(BaseModel):
    timestamp: datetime
    service: ServiceName
    level: str  # ERROR, WARN, INFO, DEBUG
    message: str
    trace_id: Optional[str] = None
    stack_trace: Optional[str] = None


class MetricDataPoint(BaseModel):
    timestamp: datetime
    service: ServiceName
    metric_name: str  # cpu_percent, memory_mb, p99_latency_ms, error_rate, connections_active
    value: float


class DeploymentEvent(BaseModel):
    deploy_id: str = Field(default_factory=lambda: uuid4().hex[:8])
    timestamp: datetime
    service: ServiceName
    change_type: ChangeType
    description: str
    commit_sha: Optional[str] = None
    author: str = "ci-bot"


# ── Agent Output Models ─────────────────────────────────────────


class AgentFinding(BaseModel):
    agent_name: str
    summary: str
    evidence: list[str] = Field(default_factory=list)
    confidence: float = 0.0  # 0.0 – 1.0
    relevant_timestamps: list[datetime] = Field(default_factory=list)
    raw_data: Optional[dict] = None


class InvestigationPlan(BaseModel):
    hypothesis: str
    tasks: list[str]
    priority_services: list[ServiceName]
    time_window_start: datetime
    time_window_end: datetime


# ── Final Report Model ──────────────────────────────────────────


class TimelineEvent(BaseModel):
    timestamp: datetime
    description: str
    source: str  # which agent or system produced this


class RCAReport(BaseModel):
    investigation_id: str = Field(default_factory=lambda: uuid4().hex[:16])
    alert: Alert
    status: InvestigationStatus = InvestigationStatus.COMPLETED
    plan: Optional[InvestigationPlan] = None
    findings: list[AgentFinding] = Field(default_factory=list)
    root_cause: str = ""
    confidence: float = 0.0
    timeline: list[TimelineEvent] = Field(default_factory=list)
    recommendation: str = ""
    remediation_action: Optional[str] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    duration_seconds: float = 0.0


# ── Mock Data Container ─────────────────────────────────────────


class MockDataSet(BaseModel):
    """Container for all mock data generated by a scenario."""
    scenario_name: str
    logs: list[LogEntry] = Field(default_factory=list)
    metrics: list[MetricDataPoint] = Field(default_factory=list)
    deployments: list[DeploymentEvent] = Field(default_factory=list)
    alert: Alert
